### ISSUE TITLE
Questions about the experiments

### ISSUE THREAD

**Issue by mchen644** [AndrewZhou924/RGIB#1]
Hello, very awesome works!
Could I ask how do you test the robustness towards the label noise in detail?
Thank you if you can inspire me with the experiment design for evaluating the robustness towards both the input noise and the label noise!

**Comment by AndrewZhou924** [comment]
Hi, thanks for your interest in our work.

We follow the random split manner to divide the dataset into train, validate, and test sets. Specifically,
- The train set is added with input noise and label noise.
- The validate and test sets are added with the same set of input noise.
- The labels of validate and test sets are clean (unchanged) to guarantee a correct evaluation.

Namely, the model is trained on a noisy train set with bilateral edge noise, and then tested on an input-noisy validate/test set with clean labels. A higher test AUC indicates better robustness.

**Comment by mchen644** [comment]
Got it! Thank you for replying!
